<?php

declare(strict_types=1);

namespace Arokettu\Clock;

use DateTimeImmutable;
use Psr\Clock\ClockInterface;

final class RoundingClock implements ClockInterface
{
    const ROUND_MICROSECONDS = 0;
    const ROUND_MILLISECONDS = 1;
    const ROUND_SECONDS = 2;
    const ROUND_MINUTES = 3;
    const ROUND_HOURS = 4;
    const ROUND_DAYS = 5;
    const ROUND_WEEKS = 6;
    const ROUND_MONTHS = 7;
    const ROUND_YEARS = 8;
    const ROUND_ISO_YEARS = 9;

    private $innerClock;
    private $rounding;

    public function __construct(ClockInterface $innerClock, int $rounding)
    {
        $this->innerClock = $innerClock;
        $this->rounding = $rounding;
    }

    public function now(): DateTimeImmutable
    {
        $now = $this->innerClock->now();

        // round mcs: noop
        if ($this->rounding <= self::ROUND_MICROSECONDS) {
            return $now;
        }

        // round time
        if ($this->rounding <= self::ROUND_HOURS) {
            $ms = $this->rounding <= self::ROUND_MILLISECONDS ? \intval($now->format('v')) : 0;
            $s  = $this->rounding <= self::ROUND_SECONDS ? \intval($now->format('s')) : 0;
            $m  = $this->rounding <= self::ROUND_MINUTES ? \intval($now->format('i')) : 0;
            $h  = \intval($now->format('H'));

            if (PHP_VERSION_ID < 70100) {
                // @codeCoverageIgnoreStart
                // coverage is generated by PHP 8.1 where these hacks are not needed
                $now = DateTimeImmutable::createFromFormat('U v', $now->getTimestamp() . ' ' . $ms);
                $now = $now->setTime($h, $m, $s);
                // @codeCoverageIgnoreEnd
            } else {
                $now = $now->setTime($h, $m, $s, $ms * 1000);
            }

            return $now;
        }

        if (PHP_VERSION_ID < 70100) {
            // @codeCoverageIgnoreStart
            // coverage is generated by PHP 8.1 where these hacks are not needed
            $now = $now->setTimestamp($now->getTimestamp()); // round microseconds
            $now = $now->setTime(0, 0, 0);
            // @codeCoverageIgnoreEnd
        } else {
            $now = $now->setTime(0, 0, 0, 0);
        }

        // if days, we're done
        if ($this->rounding <= self::ROUND_DAYS) {
            return $now;
        }

        if ($this->rounding === self::ROUND_WEEKS || $this->rounding === self::ROUND_ISO_YEARS) {
            $w = $this->rounding <= self::ROUND_WEEKS ? \intval($now->format('W')) : 1;
            $y = \intval($now->format('o'));

            return $now->setISODate($y, $w);
        }

        $m = $this->rounding <= self::ROUND_MONTHS ? \intval($now->format('n')) : 1;
        $y = \intval($now->format('Y'));

        return $now->setDate($y, $m, 1);
    }
}
